### PR TITLE
Add Dungeon module and Level class

### PR DESCRIPTION
**Pull request by HeavenManySugar**
This pull request adds the Dungeon module and the Level class to the project. The Dungeon module includes the Map and Level classes, which are responsible for managing the game's levels and their elements.

### CODE REVIEW

**Comment by onon1101** [comment]
Please check your github workflows, that seems like broken when Pull Request

```
# .github/workflows/multi-system.yml
on: 
  merge_group:
  pull_request:

```

**Comment by HeavenManySugar** [comment]
As you can see, I have never modified that file.

**Comment by onon1101** [comment]
> As you can see, I have never modified that file.

yeah, It's my problem

**Comment by HeavenManySugar** [comment]
And this pull request as draft.
Please don't change it.

**Comment by onon1101** [comment]
so... , how do I know if you were finish?

**Review by onon1101 — APPROVED** [review]
it better to change to `size_t` than `int`

**Pull request merged**
