### PR TITLE
Implement A* algorithm for pathfinding in Dungeon module

### PR DESCRIPTION
**Pull request by HeavenManySugar**
This pull request adds the A* algorithm for pathfinding in the Dungeon module. 
It includes the implementation of the AStar class, which provides a FindPath() method for finding the shortest path between two points on a map. 
Additionally, it adds the IsPositionValid() and IsHasEntity() methods to the SimpleMapData class for checking if a position is valid and if it has an entity.

### CODE REVIEW

**Comment by HeavenManySugar** [comment]
TBR

**Comment by onon1101** [comment]
Is the class `Astar` not add in any enemies, like Bat ?!

**Comment by HeavenManySugar** [comment]
nothing now

**Comment by HeavenManySugar** [comment]
AStar is made for 
image

**Comment by HeavenManySugar** [comment]
And maybe I won't that it too **SMART**
I will make the cost of Movement that changes direction more expensive

**Review by onon1101 — APPROVED** [review]
ok

**Pull request merged**
