### PR TITLE
Add more enemies

### PR DESCRIPTION
**Pull request by HeavenManySugar**
This pull request refactors the enemy movement and facing logic in the game. It includes changes to the Enemy class, EnemyFactory, SimpleMapData, AStar algorithm, MapData class, and the addition of a new Skeleton enemy, Ghost enemy and Zombie enemy  . The changes improve the enemy movement behavior and add a facing direction for the enemies.

### CODE REVIEW

**Comment by HeavenManySugar** [comment]
@onon1101 PTAL

**Comment by HeavenManySugar** [comment]
Monkey will implement it after completing the combat system

**Comment by onon1101** [comment]
NAK

**Review by onon1101 — APPROVED** [review]
LGTM

**Pull request merged**
